name: "Docker Compose with Tests Action"
description: "Run your docker-compose file and excute tests inside one of the containers."
inputs:
  compose-file: # id of input
    description: "relative path to compose file(s)"
    required: false
    default: "./docker-compose.yml"
  compose-flags: # id of input
    description: "additional options to pass to `docker-compose` command"
    required: false
    default: ""
  down-flags: # id of input
    description: "additional options to pass to `docker-compose down` command"
    required: false
    default: ""
  services: # id of input
    description: "services to perform docker-compose up"
    required: false
  up-flags: # id of input
    description: "additional options to pass to `docker-compose up` command"
    required: false
    default: ""
  test-container:
    description: "Name of the container to run tests in."
    required: false
  test-command:
    description: "The command to use to execute tests."
    required: false
runs:
  using: "node16"
  main: "main.js"
  post: "post.js"
branding:
  icon: anchor
  color: blue
