name: "Docker Compose Action"
description: "Run your docker-compose file"
inputs:
  compose-file:
    description: "relative path to compose file(s)"
    required: false
    default: "./docker-compose.yml"
  compose-flags:
    description: "additional options to pass to `docker-compose` command"
    required: false
    default: ""
  down-flags:
    description: "additional options to pass to `docker-compose down` command"
    required: false
    default: ""
  services:
    description: "services to perform docker-compose up"
    required: false
  up-flags:
    description: "additional options to pass to `docker-compose up` command"
    required: false
    default: ""
runs:
  using: "node16"
  main: "main.js"
  post: "post.js"
branding:
  icon: anchor
  color: blue
