name: Internal - Checks for nodejs

on:
  workflow_call:

permissions: {}

jobs:
  test-nodejs:
    uses: hoverkraft-tech/ci-github-nodejs/.github/workflows/continuous-integration.yml@6b74a8f070140f5c120f78026d58e4c00d1b1e37 # 0.24.2
    permissions:
      contents: read
      id-token: write
      packages: read
      pull-requests: write
      security-events: write
    with:
      build: ""
      test: |
        {"coverage":"codecov"}
