name: Internal - Checks for nodejs

on:
  workflow_call:

permissions: {}

jobs:
  test-nodejs:
    uses: hoverkraft-tech/ci-github-nodejs/.github/workflows/continuous-integration.yml@9f77c58db848451f244f78047fbf779c60bb8641 # 0.23.1
    permissions:
      contents: read
      id-token: write
      packages: read
      pull-requests: write
      security-events: write
    with:
      build: ""
      test: |
        {"coverage":"codecov"}
