name: Internal - Checks for dist

on:
  workflow_call:

permissions: {}

jobs:
  check-dist:
    name: Check dist
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6.0.3
        with:
          persist-credentials: false

      - id: setup-node
        uses: hoverkraft-tech/ci-github-nodejs/actions/setup-node@6b74a8f070140f5c120f78026d58e4c00d1b1e37 # 0.24.2

      - name: Build dist/ Directory
        id: package
        run: ${{ steps.setup-node.outputs.run-script-command }} package

      # This will fail the workflow if the PR wasn't created by Dependabot.
      - name: Compare Directories
        id: diff
        run: |
          if [ "$(git diff --ignore-space-at-eol --text dist/ | wc -l)" -gt "0" ]; then
            echo "Detected uncommitted changes after package. See status below:"
            git diff --ignore-space-at-eol --text dist/
            exit 1
          fi
