name: Greetings

on:
  issues:
    types: [opened]
  pull_request:
    branches: [main]

permissions: {}

jobs:
  greetings:
    uses: hoverkraft-tech/ci-github-common/.github/workflows/greetings.yml@3a27d31e9ccefbe9609cc9165017ed100ff34a22 # 0.38.0
    permissions:
      contents: read
      issues: write
      pull-requests: write
