name: Greetings

on:
  issues:
    types: [opened]
  pull_request_target:
    branches: [main]

permissions: {}

jobs:
  greetings:
    uses: hoverkraft-tech/ci-github-common/.github/workflows/greetings.yml@b553a696531fbd36743ccbb0c76c717971b8acdb # 0.35.4
    permissions:
      contents: read
      issues: write
      pull-requests: write
