name: Greetings

on:
  issues:
    types: [opened]
  pull_request:
    branches: [main]

permissions: {}

jobs:
  greetings:
    uses: hoverkraft-tech/ci-github-common/.github/workflows/greetings.yml@2334d395217f9811699dbd4ace9d8559e4d99e0d # 0.37.3
    permissions:
      contents: read
      issues: write
      pull-requests: write
