name: Mark stale issues and pull requests

on:
  schedule:
    - cron: "30 1 * * *"

permissions: {}

jobs:
  main:
    uses: hoverkraft-tech/ci-github-common/.github/workflows/stale.yml@71b85947453f32b5d147ff3ab37351439a92d840 # 0.34.2
    permissions:
      issues: write
      pull-requests: write
